import js from '@eslint/js';
import { defineConfig } from 'eslint/config';

export const jsConfig = defineConfig({
	name: 'js',
	extends: [js.configs.recommended],
	rules: {
		'arrow-body-style': 'warn',
		'block-scoped-var': 'error',
		'default-case-last': 'error',
		'default-param-last': 'error',
		'dot-notation': 'warn',
		'func-names': ['warn', 'as-needed'],
		'func-style': ['warn', 'declaration', { allowTypeAnnotation: true }],
		'grouped-accessor-pairs': 'warn',
		'no-await-in-loop': 'error',
		'no-console': 'warn',
		'no-constructor-return': 'error',
		'no-else-return': 'warn',
		'no-empty': ['warn', { allowEmptyCatch: true }],
		'no-global-assign': 'error',
		'no-implicit-coercion': ['error', { boolean: false }],
		'no-implied-eval': 'error',
		'no-lone-blocks': 'warn',
		'no-lonely-if': 'warn',
		'no-multi-str': 'warn',
		'no-negated-condition': 'warn',
		'no-shadow-restricted-names': 'error',
		'no-throw-literal': 'error',
		'no-unassigned-vars': 'warn',
		'no-underscore-dangle': 'error',
		'no-unneeded-ternary': 'warn',
		'no-unused-expressions': ['warn', { allowTernary: true }],
		'no-useless-concat': 'warn',
		'no-useless-constructor': 'warn',
		'no-useless-rename': 'error',
		'no-useless-return': 'warn',
		'no-var': 'error',
		'object-shorthand': 'warn',
		'operator-assignment': 'warn',
		'prefer-arrow-callback': 'warn',
		'prefer-destructuring': ['warn', {
			VariableDeclarator: { array: true, object: true },
			AssignmentExpression: { array: false, object: false },
		}],
		'prefer-exponentiation-operator': 'warn',
		'prefer-template': 'warn',
		curly: ['warn', 'multi-line'],
		eqeqeq: 'error',
		yoda: 'warn',
	},
});
