import stylistic from '@stylistic/eslint-plugin';
import { defineConfig } from 'eslint/config';

export const stylisticConfig = defineConfig({
	name: 'stylistic',
	plugins: {
		'@stylistic': stylistic,
	},
	rules: {
		'@stylistic/array-bracket-newline': ['warn', 'consistent'],
		'@stylistic/array-bracket-spacing': 'warn',
		'@stylistic/array-element-newline': ['warn', 'consistent'],
		'@stylistic/arrow-parens': 'warn',
		'@stylistic/arrow-spacing': 'warn',
		'@stylistic/block-spacing': 'warn',
		'@stylistic/brace-style': 'warn',
		'@stylistic/comma-dangle': ['warn', 'always-multiline'],
		'@stylistic/comma-spacing': 'warn',
		'@stylistic/comma-style': 'warn',
		'@stylistic/computed-property-spacing': 'warn',
		'@stylistic/curly-newline': ['warn', 'always'],
		'@stylistic/dot-location': ['warn', 'property'],
		'@stylistic/eol-last': 'warn',
		'@stylistic/function-call-argument-newline': ['warn', 'consistent'],
		'@stylistic/function-call-spacing': 'warn',
		'@stylistic/function-paren-newline': ['warn', 'consistent'],
		'@stylistic/generator-star-spacing': 'warn',
		'@stylistic/implicit-arrow-linebreak': 'warn',
		'@stylistic/indent': ['warn', 'tab'],
		'@stylistic/indent-binary-ops': ['warn', 'tab'],
		'@stylistic/key-spacing': 'warn',
		'@stylistic/keyword-spacing': 'warn',
		'@stylistic/linebreak-style': 'warn',
		'@stylistic/lines-around-comment': 'warn',
		'@stylistic/lines-between-class-members': ['warn', 'always', { exceptAfterSingleLine: true }],
		'@stylistic/max-statements-per-line': 'warn',
		'@stylistic/member-delimiter-style': ['warn', { singleline: { delimiter: 'comma' } }],
		'@stylistic/multiline-comment-style': ['warn', 'separate-lines'],
		'@stylistic/multiline-ternary': ['warn', 'always-multiline'],
		'@stylistic/new-parens': 'warn',
		'@stylistic/no-extra-semi': 'warn',
		'@stylistic/no-floating-decimal': 'warn',
		'@stylistic/no-mixed-operators': 'warn',
		'@stylistic/no-mixed-spaces-and-tabs': 'warn',
		'@stylistic/no-multi-spaces': 'warn',
		'@stylistic/no-multiple-empty-lines': ['warn', { max: 1, maxEOF: 0, maxBOF: 0 }],
		'@stylistic/no-trailing-spaces': 'warn',
		'@stylistic/no-whitespace-before-property': 'warn',
		'@stylistic/nonblock-statement-body-position': 'warn',
		'@stylistic/object-curly-newline': ['warn', { consistent: true }],
		'@stylistic/object-curly-spacing': ['warn', 'always'],
		'@stylistic/object-property-newline': ['warn', { allowAllPropertiesOnSameLine: true }],
		'@stylistic/operator-linebreak': ['warn', 'before'],
		'@stylistic/padded-blocks': ['warn', 'never'],
		'@stylistic/quote-props': ['warn', 'as-needed'],
		'@stylistic/quotes': ['warn', 'single', { avoidEscape: true }],
		'@stylistic/rest-spread-spacing': 'warn',
		'@stylistic/semi': 'warn',
		'@stylistic/semi-spacing': 'warn',
		'@stylistic/semi-style': 'warn',
		'@stylistic/space-before-blocks': 'warn',
		'@stylistic/space-before-function-paren': ['warn', { named: 'never' }],
		'@stylistic/space-in-parens': 'warn',
		'@stylistic/space-infix-ops': 'warn',
		'@stylistic/space-unary-ops': 'warn',
		'@stylistic/spaced-comment': 'warn',
		'@stylistic/switch-colon-spacing': 'warn',
		'@stylistic/template-curly-spacing': 'warn',
		'@stylistic/template-tag-spacing': 'warn',
		'@stylistic/type-annotation-spacing': 'warn',
		'@stylistic/type-generic-spacing': 'warn',
		'@stylistic/type-named-tuple-spacing': 'warn',
		'@stylistic/yield-star-spacing': 'warn',
	},
});
