import js from '@eslint/js';
import stylistic from '@stylistic/eslint-plugin';
import { defineConfig, globalIgnores } from 'eslint/config';
import { createNextImportResolver } from 'eslint-import-resolver-next';
import importX from 'eslint-plugin-import-x';
import ts from 'typescript-eslint';

export default defineConfig([
	js.configs.recommended,
	// @ts-expect-error
	ts.configs.recommended,
	// @ts-expect-error
	importX.flatConfigs.typescript,
	{
		name: 'jrmajor/js',
		plugins: {
			'@stylistic': stylistic,
		},
		linterOptions: {
			reportUnusedInlineConfigs: 'warn',
			reportUnusedDisableDirectives: 'warn',
		},
		rules: {
			'arrow-body-style': 'warn',
			'block-scoped-var': 'error',
			'default-case-last': 'error',
			'default-param-last': 'error',
			'dot-notation': 'warn',
			'func-names': ['warn', 'as-needed'],
			'func-style': ['warn', 'declaration', { allowTypeAnnotation: true }],
			'grouped-accessor-pairs': 'warn',
			'no-await-in-loop': 'error',
			'no-console': 'warn',
			'no-constructor-return': 'error',
			'no-else-return': 'warn',
			'no-global-assign': 'error',
			'no-implicit-coercion': ['error', { boolean: false }],
			'no-implied-eval': 'error',
			'no-lone-blocks': 'warn',
			'no-lonely-if': 'warn',
			'no-multi-str': 'warn',
			'no-negated-condition': 'warn',
			'no-shadow-restricted-names': 'error',
			'no-throw-literal': 'error',
			'no-unassigned-vars': 'warn',
			'no-underscore-dangle': 'error',
			'no-unneeded-ternary': 'warn',
			'no-unused-expressions': ['warn', { allowTernary: true }],
			'no-useless-concat': 'warn',
			'no-useless-constructor': 'warn',
			'no-useless-rename': 'error',
			'no-useless-return': 'warn',
			'no-var': 'error',
			'object-shorthand': 'warn',
			'operator-assignment': 'warn',
			'prefer-arrow-callback': 'warn',
			'prefer-destructuring': ['warn', {
				VariableDeclarator: { array: true, object: true },
				AssignmentExpression: { array: false, object: false },
			}],
			'prefer-exponentiation-operator': 'warn',
			'prefer-template': 'warn',
			curly: ['warn', 'multi-line'],
			eqeqeq: 'error',
			yoda: 'warn',

			// stylistic
			'@stylistic/array-bracket-newline': ['warn', 'consistent'],
			'@stylistic/array-bracket-spacing': 'warn',
			'@stylistic/array-element-newline': ['warn', 'consistent'],
			'@stylistic/arrow-parens': 'warn',
			'@stylistic/arrow-spacing': 'warn',
			'@stylistic/block-spacing': 'warn',
			'@stylistic/brace-style': 'warn',
			'@stylistic/comma-dangle': ['warn', 'always-multiline'],
			'@stylistic/comma-spacing': 'warn',
			'@stylistic/comma-style': 'warn',
			'@stylistic/computed-property-spacing': 'warn',
			'@stylistic/curly-newline': ['warn', 'always'],
			'@stylistic/dot-location': ['warn', 'property'],
			'@stylistic/eol-last': 'warn',
			'@stylistic/func-call-spacing': 'warn',
			'@stylistic/function-call-argument-newline': ['warn', 'consistent'],
			'@stylistic/function-call-spacing': 'warn',
			'@stylistic/function-paren-newline': ['warn', 'consistent'],
			'@stylistic/generator-star-spacing': 'warn',
			'@stylistic/implicit-arrow-linebreak': 'warn',
			'@stylistic/indent': ['warn', 'tab'],
			'@stylistic/indent-binary-ops': ['warn', 'tab'],
			'@stylistic/key-spacing': 'warn',
			'@stylistic/keyword-spacing': 'warn',
			'@stylistic/linebreak-style': 'warn',
			'@stylistic/lines-around-comment': 'warn',
			'@stylistic/lines-between-class-members': ['warn', 'always', { exceptAfterSingleLine: true }],
			'@stylistic/max-statements-per-line': 'warn',
			'@stylistic/member-delimiter-style': ['warn', { singleline: { delimiter: 'comma' } }],
			'@stylistic/multiline-comment-style': ['warn', 'separate-lines'],
			'@stylistic/multiline-ternary': ['warn', 'always-multiline'],
			'@stylistic/new-parens': 'warn',
			'@stylistic/no-extra-semi': 'warn',
			'@stylistic/no-floating-decimal': 'warn',
			'@stylistic/no-mixed-operators': 'warn',
			'@stylistic/no-mixed-spaces-and-tabs': 'warn',
			'@stylistic/no-multi-spaces': 'warn',
			'@stylistic/no-multiple-empty-lines': ['warn', { max: 1, maxEOF: 0, maxBOF: 0 }],
			'@stylistic/no-trailing-spaces': 'warn',
			'@stylistic/no-whitespace-before-property': 'warn',
			'@stylistic/nonblock-statement-body-position': 'warn',
			'@stylistic/object-curly-newline': ['warn', { consistent: true }],
			'@stylistic/object-curly-spacing': ['warn', 'always'],
			'@stylistic/object-property-newline': ['warn', { allowAllPropertiesOnSameLine: true }],
			'@stylistic/operator-linebreak': ['warn', 'before'],
			'@stylistic/padded-blocks': ['warn', 'never'],
			'@stylistic/quote-props': ['warn', 'as-needed'],
			'@stylistic/quotes': ['warn', 'single', { avoidEscape: true }],
			'@stylistic/rest-spread-spacing': 'warn',
			'@stylistic/semi': 'warn',
			'@stylistic/semi-spacing': 'warn',
			'@stylistic/semi-style': 'warn',
			'@stylistic/space-before-blocks': 'warn',
			'@stylistic/space-before-function-paren': ['warn', { named: 'never' }],
			'@stylistic/space-in-parens': 'warn',
			'@stylistic/space-infix-ops': 'warn',
			'@stylistic/space-unary-ops': 'warn',
			'@stylistic/spaced-comment': 'warn',
			'@stylistic/switch-colon-spacing': 'warn',
			'@stylistic/template-curly-spacing': 'warn',
			'@stylistic/template-tag-spacing': 'warn',
			'@stylistic/type-annotation-spacing': 'warn',
			'@stylistic/type-generic-spacing': 'warn',
			'@stylistic/type-named-tuple-spacing': 'warn',
			'@stylistic/yield-star-spacing': 'warn',

			// imports
			'import-x/export': 'error',
			'import-x/extensions': ['warn', 'ignorePackages', { ts: 'never' }],
			'import-x/first': 'warn',
			// considerComments handles comments after and between the same
			'import-x/newline-after-import': 'warn',
			'import-x/no-absolute-path': 'error',
			// causes parse errors in svelte plugin
			'import-x/no-cycle': 'off',
			// broken for svelte subpackages
			'import-x/no-duplicates': 'off',
			'import-x/no-empty-named-blocks': 'warn',
			'import-x/no-extraneous-dependencies': 'error',
			'import-x/no-mutable-exports': 'error',
			'import-x/no-self-import': 'error',
			'import-x/no-useless-path-segments': 'warn',
			'import-x/no-named-default': 'warn',
			'import-x/order': ['warn', {
				alphabetize: { order: 'asc' },
				named: { enabled: true, types: 'types-last' },
				'newlines-between': 'never',
				groups: [
					'builtin',
					'external',
					'internal',
					'unknown',
					'parent',
					'sibling',
					'index',
					'object',
				],
				pathGroups: [
					{ pattern: 'svelte', group: 'external', position: 'before' },
					{ pattern: 'svelte/**', group: 'external', position: 'before' },
					{ pattern: '@/types/**', group: 'internal', position: 'after' },
					{ pattern: '@/helpers/**', group: 'internal', position: 'after' },
					{ pattern: '@/Layouts/**', group: 'internal', position: 'after' },
					{ pattern: '@/Components/**', group: 'internal', position: 'after' },
				],
				pathGroupsExcludedImportTypes: ['builtin'],
				warnOnUnassignedImports: true,
			}],
		},
		settings: {
			'import-x/resolver-next': [createNextImportResolver()],
		},
	},
	{
		name: 'jrmajor/ts',
		rules: {
			// eslint base rule now handles ts syntax
			'@typescript-eslint/no-unused-expressions': 'off',

			// disable some defaults
			'@typescript-eslint/ban-ts-comment': 'off',
			'@typescript-eslint/no-explicit-any': 'off',

			// stylistic
			'@typescript-eslint/array-type': ['warn', { default: 'array-simple', readonly: 'array-simple' }],
			'@typescript-eslint/consistent-generic-constructors': 'warn',
			'@typescript-eslint/consistent-indexed-object-style': 'warn',
			'@typescript-eslint/consistent-type-assertions': 'warn',
			'@typescript-eslint/prefer-for-of': 'warn',
			'@typescript-eslint/prefer-function-type': 'warn',
		},
	},
	globalIgnores([
		'vendor',
		'rolldown.config.*.js',
		'vite.config.[jt]s.timestamp-*',
	], 'jrmajor/ignores'),
]);
