name: CI

on:
  pull_request:
  push:
    branches-ignore: [main]

jobs:
  types:
    name: Types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22.20.0

      - name: Install npm dependencies
        run: pnpm install

      - name: Check types
        run: pnpm check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22.20.0

      - name: Install npm dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

  integration:
    name: Integration / ${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - arbor
          - bajki-muza
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          path: eslint-config

      - name: Checkout the other repo
        uses: actions/checkout@v5
        with:
          repository: jrmajor/${{ matrix.project }}
          path: integration

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: integration/package.json

      - name: Install npm dependencies
        working-directory: integration
        run: pnpm add -D file:../eslint-config && pnpm upgrade eslint

      - name: Run ESLint
        continue-on-error: true
        working-directory: integration
        run: pnpm lint --fix

      - name: Show diff
        working-directory: integration
        run:  git diff --color=always -- . ':(exclude)package.json' ':(exclude)pnpm-lock.yaml'
